No single letter variables
pandas-dev/pandas-dev-flaker pull request #25
Opened 2021-06-19 19:24 UTC by klssmith

This allows `_` to be used as a variable name, since it is conventionally
used for throwaway variables, but does not allow any other single letter
variables.

The `target` method of `ast.Assigns` will normally contain a list of nodes,
however for an unpacking assignment (such as `'a,b = c'`) it will contain
an `ast.Tuple` or an `ast.List` so we need to cover for all cases.

2021-06-19 19:25 UTC, klssmith commented
@MarcoGorelli This is giving an error with the mypy precommit hook (`error: "expr" has no attribute "id”` on line 22 of single_letter_variables.py) which I can’t figure out. It’s also more complicated than originally discussed to cover for a few edge cases, so I’m not sure if this is still along the right lines or not.

2021-06-19 19:50 UTC, MarcoGorelli requested changes
Awesome work, I'm really impressed you figured this all out!

For the `mypy` issue, we just need to "help" mypy and tell it that the target elements are `ast.Name`s, and hence that they have the `id` attribute. You probably want to write it like this:
```python
    for item in assignment_names:
        if isinstance(item, ast.Name) and item.id != "_" and len(item.id) == 1:
            yield node.lineno, node.col_offset, MSG
```

cc @jbrockmendel in case you have comments - this'll raise an error all over the place in pandas, but it can be fixed incrementally

2021-06-20 01:36 UTC, jbrockmendel commented
This is pretty neat.  `_` makes sense to special-case.  Maybe also e.g. `for i in range(...)`? (i know we do that a lot in the cython code)

2021-06-20 07:07 UTC, MarcoGorelli commented
Thanks for taking a look - `for i in range` wouldn't be covered by this, as that's `ast.For` rather than `ast.Assign`

@klssmith if you mark this as "ready for review" we can merge it

2021-06-20 09:04 UTC, klssmith commented
Thanks for the comments.

@MarcoGorelli I've made the change needed to pass the mypy precommit check. I've not changed this to ready to review just yet because I've noticed that the `col_offset` in the error message can be misleading in a few situations. A file with this line
```python
abc, d = (5, 6)
```
gives the warning of 
```
test.py:1:1: PDF023 found assignment to single-letter variable
```
Since the single letter variable is at col_offset 6, I assume the message should read `test.py:1:6: PDF023 ...` in this case? If so, I can take a look at how the col_offset in error message can be fixed.

2021-06-20 10:16 UTC, MarcoGorelli commented
when you're in the `for` loop, does `item` have `.lineno` and `coloffset` attributes? If so, perhaps use those in the message?

2021-06-20 19:50 UTC, klssmith commented
👍 I was able to replace `yield node.lineno, node.col_offset, MSG` with `yield item.lineno, item.col_offset, MSG` as you suggested to get the col_offset working.

2021-06-20 19:53 UTC, MarcoGorelli approved these changes
Awesome work! Thanks @klssmith !

If you enjoyed this kind of work (ast-parsing), I'd suggest you have a look at [pyupgrade](https://github.com/asottile/pyupgrade) too - their maintainer is amazing, I've learned a ton from contributing there

2021-06-20 19:54 UTC, merged

2021-06-20 19:56 UTC, klssmith commented
Thanks for the help @MarcoGorelli! I will check out pyupgrade